// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.25.1";

// src/lib/mcp/tools/list-medications.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.25.1";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.98.0";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/shared.ts
function resolvePatientId(ctx, patientId) {
  const id = patientId?.trim() || ctx.getUserId();
  if (!id) throw new Error("No patient id available for this request");
  return id;
}
function textResult(payload) {
  return { content: [{ type: "text", text: JSON.stringify(payload) }] };
}
function errorResult(message) {
  return { content: [{ type: "text", text: message }], isError: true };
}

// src/lib/mcp/tools/list-medications.ts
var list_medications_default = defineTool({
  name: "list_medications",
  title: "List medications",
  description: "List active medications for a patient (defaults to the signed-in user).",
  inputSchema: {
    patient_id: z.string().uuid().optional().describe("Patient user id. Omit to use the signed-in user.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ patient_id }, ctx) => {
    if (!ctx.isAuthenticated()) return errorResult("Not authenticated");
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("medications").select("id,name,dosage,frequency,time_of_day,notes,is_active").eq("patient_id", resolvePatientId(ctx, patient_id)).eq("is_active", true).order("name");
    return error ? errorResult(error.message) : textResult({ medications: data ?? [] });
  }
});

// src/lib/mcp/tools/list-daily-tasks.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.25.1";
import { z as z2 } from "npm:zod@^3.25.76";
var list_daily_tasks_default = defineTool2({
  name: "list_daily_tasks",
  title: "List daily tasks",
  description: "List a patient's care tasks for a given date (defaults to today and the signed-in user).",
  inputSchema: {
    patient_id: z2.string().uuid().optional().describe("Patient user id. Omit to use the signed-in user."),
    task_date: z2.string().optional().describe("Date in YYYY-MM-DD form. Omit for today.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ patient_id, task_date }, ctx) => {
    if (!ctx.isAuthenticated()) return errorResult("Not authenticated");
    const date = task_date?.trim() || (/* @__PURE__ */ new Date()).toISOString().slice(0, 10);
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("daily_tasks").select("id,title,description,category,scheduled_time,is_completed,completed_at,task_date").eq("patient_id", resolvePatientId(ctx, patient_id)).eq("task_date", date).order("scheduled_time", { ascending: true });
    return error ? errorResult(error.message) : textResult({ task_date: date, tasks: data ?? [] });
  }
});

// src/lib/mcp/tools/complete-daily-task.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.25.1";
import { z as z3 } from "npm:zod@^3.25.76";
var complete_daily_task_default = defineTool3({
  name: "complete_daily_task",
  title: "Complete daily task",
  description: "Mark one of the patient's daily care tasks as completed.",
  inputSchema: {
    task_id: z3.string().uuid().describe("Id of the daily task to mark completed.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: true, openWorldHint: false },
  handler: async ({ task_id }, ctx) => {
    if (!ctx.isAuthenticated()) return errorResult("Not authenticated");
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("daily_tasks").update({ is_completed: true, completed_at: (/* @__PURE__ */ new Date()).toISOString() }).eq("id", task_id).select("id,title,is_completed,completed_at");
    if (error) return errorResult(error.message);
    if (!data?.length) return errorResult("Task not found or not accessible.");
    return textResult({ task: data[0] });
  }
});

// src/lib/mcp/tools/log-mood-entry.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.25.1";
import { z as z4 } from "npm:zod@^3.25.76";
var log_mood_entry_default = defineTool4({
  name: "log_mood_entry",
  title: "Log mood entry",
  description: "Record a mood diary entry for a patient.",
  inputSchema: {
    mood: z4.string().trim().min(1).describe("Mood label, e.g. calm, anxious, happy."),
    energy_level: z4.number().int().optional().describe("Energy level from 1 (low) to 5 (high)."),
    notes: z4.string().optional().describe("Optional free-text notes."),
    symptoms: z4.array(z4.string()).optional().describe("Optional list of observed symptoms."),
    patient_id: z4.string().uuid().optional().describe("Patient user id. Omit to use the signed-in user.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ mood, energy_level, notes, symptoms, patient_id }, ctx) => {
    if (!ctx.isAuthenticated()) return errorResult("Not authenticated");
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("mood_entries").insert({
      patient_id: resolvePatientId(ctx, patient_id),
      mood,
      energy_level: energy_level ?? null,
      notes: notes ?? null,
      symptoms: symptoms ?? null
    }).select("id,mood,energy_level,notes,symptoms,entry_date");
    return error ? errorResult(error.message) : textResult({ entry: data?.[0] });
  }
});

// src/lib/mcp/tools/list-recent-vitals.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.25.1";
import { z as z5 } from "npm:zod@^3.25.76";
var list_recent_vitals_default = defineTool5({
  name: "list_recent_vitals",
  title: "List recent vitals",
  description: "List the most recent recorded vitals for a patient.",
  inputSchema: {
    patient_id: z5.string().uuid().optional().describe("Patient user id. Omit to use the signed-in user."),
    limit: z5.number().int().optional().describe("How many readings to return (1-50, default 10).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ patient_id, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return errorResult("Not authenticated");
    const take = Math.min(Math.max(limit ?? 10, 1), 50);
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("patient_vitals").select("*").eq("patient_id", resolvePatientId(ctx, patient_id)).order("recorded_at", { ascending: false }).limit(take);
    return error ? errorResult(error.message) : textResult({ vitals: data ?? [] });
  }
});

// src/lib/mcp/tools/list-appointments.ts
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.25.1";
import { z as z6 } from "npm:zod@^3.25.76";
var list_appointments_default = defineTool6({
  name: "list_appointments",
  title: "List appointments",
  description: "List upcoming appointments for a patient.",
  inputSchema: {
    patient_id: z6.string().uuid().optional().describe("Patient user id. Omit to use the signed-in user."),
    limit: z6.number().int().optional().describe("How many appointments to return (1-50, default 10).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ patient_id, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return errorResult("Not authenticated");
    const take = Math.min(Math.max(limit ?? 10, 1), 50);
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("appointments").select("*").eq("patient_id", resolvePatientId(ctx, patient_id)).order("appointment_date", { ascending: true }).limit(take);
    return error ? errorResult(error.message) : textResult({ appointments: data ?? [] });
  }
});

// src/lib/mcp/index.ts
var projectRef = "sdwbtlfsrlgomxwnrrzq";
var mcp_default = defineMcp({
  name: "memory-compass",
  title: "Memory Compass",
  version: "0.1.0",
  instructions: "Tools for Memory Compass, an Alzheimer's care platform. Read medications, daily care tasks, vitals and appointments for the signed-in patient (or an assigned patient), mark tasks complete, and log mood diary entries. All access is scoped by the app's row-level security, so only data the signed-in user may see is returned.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    list_medications_default,
    list_daily_tasks_default,
    complete_daily_task_default,
    log_mood_entry_default,
    list_recent_vitals_default,
    list_appointments_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.25.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
